import type { CategoryResult, CheckStatus } from '@/types/audit'

function blank(id: string, label: string, sfccValue?: string) {
  return { id, label, status: 'fail' as CheckStatus, sfccValue }
}

export function buildManualTemplate(): CategoryResult[] {
  return [
    {
      id: 'homepage',
      name: 'Homepage Experience',
      icon: '🏠',
      score: 0,
      maxScore: 12,
      checks: [
        blank('hero-banner', 'Hero banner / promotional content', "Einstein Recommendations & Page Designer enable dynamic, targeted hero banners with A/B testing — increasing click-through rates by up to 20%."),
        blank('homepage-recommendations', 'Personalized product recommendations', "Einstein Product Recommendations delivers AI-driven personalization shown to increase AOV by 15–30%."),
        blank('search-bar', 'Prominent search bar', "Einstein Search delivers predictive search with AI-powered autocomplete — reducing zero-result searches by 40%."),
        blank('category-nav', 'Featured categories navigation'),
        blank('trust-signals', 'Trust signals (reviews, security badges)', "Salesforce Commerce Cloud integrates with leading review platforms and displays trust badges natively — reducing bounce rates on landing pages."),
        blank('live-chat', 'Live chat / support widget', "Service Cloud integration with Commerce enables embedded live chat, reducing cart abandonment by surfacing help at critical moments."),
      ],
    },
    {
      id: 'search',
      name: 'Search & Navigation',
      icon: '🔍',
      score: 0,
      maxScore: 12,
      checks: [
        blank('autocomplete', 'Search autocomplete / typeahead', "Einstein Search provides AI-powered autocomplete that surfaces relevant products as the shopper types — increasing search conversion by 35%."),
        blank('faceted-search', 'Faceted / filtered search results', "Commerce Cloud's search faceting allows shoppers to narrow results by size, color, price, and brand — reducing time-to-purchase."),
        blank('results-quality', 'Search results show images and prices', "Commerce Cloud's search grid presents rich product tiles with imagery, pricing, and ratings — driving higher click-through from search."),
        blank('no-results', 'No-results handling (alternative suggestions)', "Einstein Search returns intelligent suggestions and alternative products, preventing dead ends that cause 68% of shoppers to leave."),
        blank('breadcrumbs', 'Breadcrumb navigation'),
        blank('mega-menu', 'Mega menu / category navigation', "Page Designer enables drag-and-drop mega menu creation with rich imagery and promotional spots — improving category discoverability."),
      ],
    },
    {
      id: 'plp',
      name: 'Product Listing Pages',
      icon: '📋',
      score: 0,
      maxScore: 12,
      checks: [
        blank('plp-filters', 'Filter & sort controls', "Commerce Cloud's native faceting and sort controls help shoppers narrow results, lifting conversion by 25%."),
        blank('quick-view', 'Quick view modal', "Quick view reduces friction and enables add-to-cart without losing browse context."),
        blank('hover-image', 'Product image swap on hover'),
        blank('pagination', 'Pagination or infinite scroll'),
        blank('product-badges', 'Product badges (sale, new, bestseller)'),
        blank('wishlist-listing', 'Wishlist / save from listing', "Native wishlist functionality creates retargeting opportunities — saved items have 40% higher purchase intent."),
      ],
    },
    {
      id: 'pdp',
      name: 'Product Detail Pages',
      icon: '📦',
      score: 0,
      maxScore: 16,
      checks: [
        blank('product-images', 'High-quality images (zoom, multiple angles)', "Commerce Cloud supports up to 16 product angles with built-in zoom — reducing return rates by 22%."),
        blank('product-video', 'Product video', "Product videos increase conversion rates by up to 80%."),
        blank('variant-selector', 'Variant selector (size, color, etc.)'),
        blank('stock-indicator', 'Stock / availability indicator'),
        blank('reviews-ratings', 'Customer reviews & ratings', "88% of consumers trust online reviews as much as personal recommendations."),
        blank('pdp-recommendations', '"You may also like" recommendations', "Einstein Recommendations on the PDP increases AOV by 15-30%."),
        blank('social-sharing', 'Social sharing'),
        blank('delivery-estimate', 'Delivery estimate shown'),
      ],
    },
    {
      id: 'cart',
      name: 'Cart & Checkout',
      icon: '🛒',
      score: 0,
      maxScore: 12,
      checks: [
        blank('guest-checkout', 'Guest checkout available', "34% of shoppers abandon when forced to create an account."),
        blank('coupon-code', 'Promo / coupon code field'),
        blank('multi-payment', 'Multiple payment methods (card, PayPal, BNPL)', "Commerce Cloud integrates with 40+ payment providers via the LINK marketplace."),
        blank('digital-wallets', 'Apple Pay / Google Pay', "Digital wallet checkout reduces checkout time to under 30 seconds."),
        blank('order-summary', 'Order summary visible'),
        blank('address-autocomplete', 'Address autocomplete'),
      ],
    },
    {
      id: 'personalization',
      name: 'Personalization & AI',
      icon: '🤖',
      score: 0,
      maxScore: 10,
      checks: [
        blank('recs-engine', 'Product recommendations engine visible', "Einstein Product Recommendations uses AI to surface the right product to the right shopper — customers who click recommendations are 4.5x more likely to purchase."),
        blank('recently-viewed', 'Recently viewed products', "Recently viewed widgets recapture browse sessions — Commerce Cloud stores session history and surfaces it across devices with shopper identity resolution."),
        blank('personalized-content', 'Personalized content based on browse history', "Einstein Behavioral Targeting enables real-time content personalization — personalized homepages lift engagement by 55% vs. one-size-fits-all."),
        blank('dynamic-banners', 'Dynamic banners / targeted promotions', "Page Designer + Einstein enables merchandisers to publish targeted promotions by segment, geography, or behavior — no developer required."),
        blank('abandoned-cart-signals', 'Abandoned cart recovery signals', "Marketing Cloud + Commerce Cloud triggers automated abandoned cart emails within 1 hour of abandonment — recovering an average of 5–15% of lost revenue."),
      ],
    },
    {
      id: 'mobile',
      name: 'Mobile Experience',
      icon: '📱',
      score: 0,
      maxScore: 10,
      checks: [
        blank('responsive', 'Responsive / mobile-optimized layout', "60%+ of ecommerce traffic is mobile. Commerce Cloud's Storefront Reference Architecture (SFRA) is mobile-first by default."),
        blank('mobile-nav', 'Mobile-friendly navigation', "SFRA includes a responsive hamburger navigation out-of-the-box, optimized for thumb-reach zones on mobile."),
        blank('touch-targets', 'Touch-friendly tap targets (44px+)', "Undersized tap targets cause mis-taps and frustration. Commerce Cloud's component library follows WCAG 2.1 AA touch target guidelines."),
        blank('pwa', 'PWA install prompt or app banner', "PWA storefronts built on Commerce Cloud's Storefront Next deliver app-like performance with 2x faster load times and offline browsing capability."),
        blank('mobile-checkout', 'Mobile-optimized checkout flow', "Commerce Cloud Checkout is optimized for mobile with single-page checkout, autofill support, and native payment integration — reducing mobile checkout abandonment by 30%."),
      ],
    },
    {
      id: 'performance',
      name: 'Page Performance',
      icon: '⚡',
      score: 0,
      maxScore: 10,
      checks: [
        blank('https', 'HTTPS enforced'),
        blank('lazy-images', 'Images use lazy loading'),
        blank('image-sizing', 'Images served at appropriate resolution'),
        blank('render-blocking', 'Minimal render-blocking resources'),
        blank('viewport-meta', 'Viewport meta tag present'),
      ],
    },
    {
      id: 'seo',
      name: 'SEO & Discovery',
      icon: '🎯',
      score: 0,
      maxScore: 12,
      checks: [
        blank('title-tag', 'Page title tag present and unique'),
        blank('meta-description', 'Meta description present', "Commerce Cloud auto-generates SEO meta tags from product data — ensuring every page, PLP, and PDP has optimized descriptions without manual effort."),
        blank('open-graph', 'Open Graph tags (social sharing)', "Commerce Cloud auto-populates Open Graph tags from product data — ensuring rich previews when pages are shared on social media."),
        blank('structured-data', 'Structured data / Schema.org markup', "Commerce Cloud SFRA generates Product, BreadcrumbList, and Organization schema markup automatically — enabling Google Rich Results (ratings stars in SERPs)."),
        blank('canonical', 'Canonical URLs present', "Commerce Cloud automatically generates canonical URLs to prevent duplicate content penalties — critical for filtered/sorted pages that can create 100s of URL variants."),
        blank('h1', 'Single H1 heading on page'),
      ],
    },
    {
      id: 'loyalty',
      name: 'Loyalty & Engagement',
      icon: '⭐',
      score: 0,
      maxScore: 10,
      checks: [
        blank('loyalty-program', 'Loyalty / rewards program visible', "Loyalty Management on the Salesforce Platform integrates natively with Commerce Cloud — loyalty members spend 67% more than non-members."),
        blank('wishlist', 'Wishlist functionality', "Commerce Cloud's native wishlist syncs across devices and integrates with Marketing Cloud for 'back in stock' and 'price drop' email triggers."),
        blank('email-capture', 'Newsletter / email capture', "Email remains the highest-ROI marketing channel. Commerce Cloud + Marketing Cloud enables seamless list growth with segmentation from day one."),
        blank('account-features', 'Customer account (order history, saved addresses)', "Commerce Cloud's shopper identity model enables unified profiles — combining purchase history, browse behavior, and loyalty data for personalized experiences."),
        blank('social-proof', 'Social proof elements ("X people viewing")', "Real-time social proof widgets (powered by Commerce Cloud's activity stream) create urgency and validate purchasing decisions — increasing conversion by 10–15%."),
      ],
    },
    {
      id: 'vitals',
      name: 'Core Web Vitals',
      icon: '📊',
      score: 0,
      maxScore: 16,
      checks: [
        blank('lcp', 'Largest Contentful Paint (LCP)', "Storefront Next (PWA) on a CDN-cached edge delivers LCP under 1.5s — a direct Google ranking signal."),
        blank('inp', 'Interaction to Next Paint (INP)', "Storefront Next's lightweight React architecture keeps INP well under 200ms."),
        blank('cls', 'Cumulative Layout Shift (CLS)', "Commerce Cloud's SFRA and Storefront Next reserve explicit dimensions for images — keeping CLS near zero."),
        blank('fcp', 'First Contentful Paint (FCP)', "Commerce Cloud uses server-side rendering and critical-CSS inlining to paint content instantly."),
        blank('ttfb', 'Time to First Byte (TTFB)', "Commerce Cloud's global CDN and page-level caching reduce TTFB to under 200ms for cached pages."),
        blank('tbt', 'Total Blocking Time (TBT)', "Commerce Cloud's code-splitting and deferred third-party scripts keep TBT minimal."),
        blank('lh-score', 'Lighthouse Performance Score', "Commerce Cloud's Storefront Next consistently achieves 90+ out-of-the-box with optimised build pipelines."),
        blank('speed-index', 'Speed Index'),
      ],
    },
    {
      id: 'ai-readiness',
      name: 'AI Readiness',
      icon: '🧠',
      score: 0,
      maxScore: 12,
      checks: [
        blank('ai-product-data', 'Product Data Quality (25%)', "Salesforce Commerce Cloud with Einstein AI provides the structured product data and open data model to close this gap."),
        blank('ai-discoverability', 'AI Discoverability (20%)', "Commerce Cloud's metadata framework and semantic content tools improve LLM-readable structure."),
        blank('ai-conversational', 'Conversational Commerce (20%)', "Agentforce Shopping Agents enable natural language product discovery and guided selling natively."),
        blank('ai-structured-data', 'Structured Data (15%)', "Commerce Cloud SFRA auto-generates Schema.org Product, Offer, and Review markup for rich AI parsing."),
        blank('ai-semantic-seo', 'Semantic SEO (10%)', "Commerce Cloud's content management tools support topic-depth and entity-rich content structures."),
        blank('ai-content-depth', 'Content Depth (10%)', "Commerce Cloud's content management enables buying guides, FAQs, and educational content that helps AI systems understand product context."),
      ],
    },
  ]
}
